// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9kiQMKOWxSg-1e9FT2Glg-8aQPCHibDY',
    appId: '1:941102094075:android:b47a030cfea4c35818425e',
    messagingSenderId: '941102094075',
    projectId: 'total-cricinfo-97212',
    storageBucket: 'total-cricinfo-97212.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLdUiVfpQNSmbBzWZxSqGLyIdP6t2rrhA',
    appId: '1:832805352412:web:7c53d335bd3401da585519',
    messagingSenderId: '832805352412',
    projectId: 'cricblizz-e5f68',
    authDomain: 'cricblizz-e5f68.firebaseapp.com',
    storageBucket: 'cricblizz-e5f68.firebasestorage.app',
    measurementId: 'G-KSNDNQT8GH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49C8nkZ8ErzBflP_STF92ROJVr2ONwWw',
    appId: '1:832805352412:ios:ed353e6e4dd761be585519',
    messagingSenderId: '832805352412',
    projectId: 'cricblizz-e5f68',
    storageBucket: 'cricblizz-e5f68.firebasestorage.app',
    iosBundleId: 'com.example.sixcricCricketScore',
  );

}